variables:
  CONTAINER_BRANCH_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_REF_SLUG
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:latest
  CONTAINER_TAGGED_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG
  DOCKER_HOST: tcp://127.0.0.1:2375

stages:
  - test
  - build
  - testing
  - prod

.docker-build: &docker-build
  stage: build
  allow_failure: false
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - docker:dind

# Common k8s elements
.k8s: &k8s
  image: google/cloud-sdk:latest
  allow_failure: false
  before_script:
    - echo -n "${__k8s_prod_sa_key}" | base64 -d > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project coinninja-prod
    - gcloud config set compute/zone us-central1-c
    - gcloud container clusters get-credentials prod-01
    - kubectl config current-context

.k8s-deploy: &branch-deploy
  script: |
    export CURRENT_IMAGE=$(kubectl -n ${CI_ENVIRONMENT_SLUG}-public get deployment ${CI_PROJECT_NAME}-server -o=jsonpath='{$.spec.template.spec.containers[0].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_BRANCH_IMAGE}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_BRANCH_IMAGE}'"
      kubectl -n ${CI_ENVIRONMENT_SLUG}-public set image deployment/${CI_PROJECT_NAME}-server ${CI_PROJECT_NAME}=${CONTAINER_BRANCH_IMAGE} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=${CI_ENVIRONMENT_SLUG}-public patch deployment ${CI_PROJECT_NAME}-server -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n ${CI_ENVIRONMENT_SLUG}-public rollout status deployment ${CI_PROJECT_NAME}-server -w
  only:
    - branches@backend/blocc
  except:
    - master
    - develop

.k8s-deploy: &tag-deploy
  script: |
    export CURRENT_IMAGE=$(kubectl -n ${CI_ENVIRONMENT_SLUG}-public get deployment ${CI_PROJECT_NAME}-server -o=jsonpath='{$.spec.template.spec.containers[0].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_TAGGED_IMAGE}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_TAGGED_IMAGE}'"
      kubectl -n ${CI_ENVIRONMENT_SLUG}-public set image deployment/${CI_PROJECT_NAME}-server ${CI_PROJECT_NAME}=${CONTAINER_TAGGED_IMAGE} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=${CI_ENVIRONMENT_SLUG}-public patch deployment ${CI_PROJECT_NAME}-server -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n ${CI_ENVIRONMENT_SLUG}-public rollout status deployment ${CI_PROJECT_NAME}-server -w
  only:
    - tags@backend/blocc
  except:
    - branches

.k8s-deploy: &latest-deploy
  script: |
    export CURRENT_IMAGE=$(kubectl -n ${CI_ENVIRONMENT_SLUG}-public get deployment ${CI_PROJECT_NAME}-server -o=jsonpath='{$.spec.template.spec.containers[0].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_LATEST_IMAGE}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_LATEST_IMAGE}'"
      kubectl -n ${CI_ENVIRONMENT_SLUG}-public set image deployment/${CI_PROJECT_NAME}-server ${CI_PROJECT_NAME}=${CONTAINER_LATEST_IMAGE} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=${CI_ENVIRONMENT_SLUG}-public patch deployment ${CI_PROJECT_NAME}-server -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n ${CI_ENVIRONMENT_SLUG}-public rollout status deployment ${CI_PROJECT_NAME}-server -w
  only:
    - develop@backend/blocc


test:
  stage: test
  image: golang:1.11-alpine3.8
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .cache
  script:
    - apk add --update-cache make git protobuf protobuf-dev curl
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH=$PATH:$GOPATH/bin
    - CGO_ENABLED=0 make test

latest:
  <<: *docker-build
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --pull --tag $CONTAINER_LATEST_IMAGE .
    - docker push $CONTAINER_LATEST_IMAGE
  only:
    - develop@backend/blocc

branch:
  <<: *docker-build
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --pull --tag $CONTAINER_BRANCH_IMAGE .
    - docker push $CONTAINER_BRANCH_IMAGE
  when: manual
  only:
    - branches@backend/blocc
  except:
    - master
    - develop
    - tags

tagged:
  <<: *docker-build
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --pull --tag $CONTAINER_TAGGED_IMAGE .
    - docker push $CONTAINER_TAGGED_IMAGE
  only:
    - tags@backend/blocc
  except:
    - branches

test-server:branch:
  <<: *k8s
  <<: *branch-deploy
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/block/info
  when: manual

test-server:latest:
  <<: *k8s
  <<: *latest-deploy
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/block/info

test-server:tag:
  <<: *k8s
  <<: *tag-deploy
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/block/info

production-server:tagged:
  <<: *k8s
  <<: *tag-deploy
  stage: prod
  environment:
    name: prod
    url: https://api.coinninja.com/api/v1/block/info
  when: manual

production-btc-block:tagged:
  <<: *k8s
  stage: prod
  environment:
    name: prod
    url: https://api.coinninja.net/api/v1/block/info
  script: |
    export CURRENT_IMAGE=$(kubectl -n indexer get deployment blocc-btc-block -o=jsonpath='{$.spec.template.spec.containers[:1].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_TAGGED_IMAGE}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_TAGGED_IMAGE}'"
      kubectl -n indexer set image deployment/blocc-btc-block blocc=${CONTAINER_TAGGED_IMAGE} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=indexer patch deployment blocc-btc-block -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n indexer rollout status deployment blocc-btc-block -w
  when: manual
  only:
    - tags@backend/blocc
  except:
    - branches

production-btc-transaction:tagged:
  <<: *k8s
  stage: prod
  environment:
    name: prod
    url: https://api.coinninja.net/api/v1/block/info
  script: |
    export CURRENT_IMAGE=$(kubectl -n indexer get deployment blocc-btc-transaction -o=jsonpath='{$.spec.template.spec.containers[:1].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_TAGGED_IMAGE}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_TAGGED_IMAGE}'"
      kubectl -n indexer set image deployment/blocc-btc-transaction blocc=${CONTAINER_TAGGED_IMAGE} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=indexer patch deployment blocc-btc-transaction -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n indexer rollout status deployment blocc-btc-transaction -w
  when: manual
  only:
    - tags@backend/blocc
  except:
    - branches
